# name: microsoft-azure-servicebus-emulator
version: '3.8'
services:
  emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    volumes:
      - "${CONFIG_PATH}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqlexpress  
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqlexpress
    networks:
      sb-emulator:
        aliases:
          - "sb-emulator"
  sqlexpress:
        container_name: "sqlexpress"
        image: "mcr.microsoft.com/mssql/server:latest"
        networks:
          sb-emulator:
            aliases:
              - "sqlexpress"
        environment:
          ACCEPT_EULA: ${ACCEPT_EULA}
          MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
networks:
  sb-emulator: