version: '3.8'

services:
  zeebe:
    image: camunda/zeebe:8.7.0
    container_name: zeebe
    environment:
      - ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT=1
      - ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR=1
      - ZEEBE_BROKER_CLUSTER_CLUSTERSIZE=1
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
    ports:
      - "26500:26500"
    networks:
      - camunda-platform

  operate:
    image: camunda/operate:8.7.0
    container_name: operate
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
    ports:
      - "8081:8080"
    networks:
      - camunda-platform

  tasklist:
    image: camunda/tasklist:8.7.0
    container_name: tasklist
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
    ports:
      - "8082:8080"
    networks:
      - camunda-platform

  connectors:
    image: camunda/connectors-bundle:8.7.0
    container_name: connectors
    environment:
      - CAMUNDA_CONNECTOR_POLLING_ENABLED=true
      - CAMUNDA_CONNECTOR_ZEEBE_GATEWAY_ADDRESS=zeebe:26500
    ports:
      - "8083:8080"
    volumes:
      - ./connectors:/opt/connectors
    networks:
      - camunda-platform

  elasticsearch:
    image: elasticsearch:7.17.10
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - camunda-platform

networks:
  camunda-platform:
